- name: conifure the cart component
  hosts: cart
  tasks:
  - name: disable the nodejs
    ansible.builtin.command: dnf disable the nodejs

  - name: enable the nodejs
    ansible.builtin.command: enable the nodejs

  - name: install the nodejs
    ansible.builtin.dnf: 
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart code
    ansible.builtin.get_url:
      url: /tmp/cart.zip https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  # this module thinks file exist on ansible control server, need to extract on remote machine    
  # remote_src: yes means file already exists in catalogue server
  - name: extract the cart code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy cart service to system directory
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes

  
  
  